### ISSUE TITLE
Cannot find module (scss)

### ISSUE THREAD

**Issue by bsastregx** [prantlf/rollup-plugin-scss-lit#1]
Hi,
I am trying to implement this plugin on the [lit typescript starter](https://github.com/lit/lit-element-starter-ts).
The issue I am having is that I am importing my scss styles on my lit element (gwds-button.ts), but getting the following error message:

`Cannot find module './gwds-button.scss' or its corresponding type declarations.ts(2307)`

![image](https://user-images.githubusercontent.com/54677414/204276535-a8327e3a-350a-4f41-8c3b-a37b37e4f479.png)

**Comment by kraus-milan** [comment]
Hi, add this to src/styles.d.ts (for other .d.ts file)

```
declare module '*.scss' {
  import { CSSResultGroup } from 'lit';
  const styles: CSSResultGroup;
  export default styles;
}
```

And add `external: [/\.s?css$/],` into rollup.config.js

**Comment by toastwaffle** [comment]
@kraus-milan I've basically copied your comment into the README with that pull request so that it's easy for people to find; hope that's okay with you :)
