### ISSUE TITLE
Rollup 4.0.2 support does not fully work need to update peerDependencies also 

### ISSUE THREAD

**Issue by SEB-Kaveh-Mehrabi** [prantlf/rollup-plugin-scss-lit#4]
"peerDependencies": {
    "lit": "^2",
    "rollup": "^2 || ^3"
  },

needs to be changed to

 "peerDependencies": {
    "lit": "^2",
    "rollup": "^2 || ^4"
  },

**Comment by ShellyDCMS** [comment]
Any update on this?

**Comment by prantlf** [comment]
Upgrade to [1.1.6](https://github.com/prantlf/rollup-plugin-scss-lit/releases/tag/v1.1.6) or the latest release, please. The 1.1.6 was released in October 2023.
